[2015-02-13 13:16:55 +0000] [25595] [INFO] Starting gunicorn 19.2.1
[2015-02-13 13:16:55 +0000] [25595] [INFO] Listening at: http://127.0.0.1:8000 (25595)
[2015-02-13 13:16:55 +0000] [25595] [INFO] Using worker: sync
[2015-02-13 13:16:55 +0000] [25601] [INFO] Booting worker with pid: 25601
[2015-02-13 13:16:55 +0000] [25604] [INFO] Booting worker with pid: 25604
[2015-02-13 14:49:55 +0000] [3080] [INFO] Starting gunicorn 19.2.1
[2015-02-13 14:49:55 +0000] [3080] [INFO] Listening at: http://127.0.0.1:8000 (3080)
[2015-02-13 14:49:55 +0000] [3080] [INFO] Using worker: sync
[2015-02-13 14:49:56 +0000] [3171] [INFO] Booting worker with pid: 3171
[2015-02-13 14:49:56 +0000] [3173] [INFO] Booting worker with pid: 3173
[2015-02-13 15:04:25 +0000] [3080] [CRITICAL] WORKER TIMEOUT (pid:3171)
[2015-02-13 15:04:25 +0000] [4141] [INFO] Booting worker with pid: 4141

2015-02-13 15:11:21,819 Request Error 
 site: site1.local
 form: {'action': u'Save',
 'cmd': u'frappe.widgets.form.save.savedocs',
 'doc': u'{"always_use_login_id_as_sender":1,"modified_by":"Administrator","name":"Outgoing Email Settings","footer":"<div style=\\"padding: 7px; text-align: right; color: #888; font-weight: bold;\\"><small>Enviado por\\n\\t<a style=\\"color: #888\\" href=\\"http://www.liberorbis.com\\">ERPNext LIBERORBIS</a></small>\\n\\n</div>","creation":"2015-02-13 23:46:38.376493","enabled":1,"modified":"2015-02-13 23:46:39.701496","doctype":"Outgoing Email Settings","use_ssl":0,"owner":"Administrator","docstatus":0,"__last_sync_on":"2015-02-13T20:08:03.554Z","__unsaved":1,"mail_server":"mail.liberorbis.com","mail_port":587,"mail_login":"erpnext@liberorbis.com","mail_password":"liberorbis2015","auto_email_id":"erpnext@liberorbis.com"}'}

Traceback (innermost last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 49, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 66, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 89, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 532, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/widgets/form/save.py", line 18, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 183, in save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 437, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 412, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 496, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 479, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 406, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/outgoing_email_settings/outgoing_email_settings.py", line 29, in validate
    sess = smtpserver.sess
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/email_lib/smtp.py", line 85, in sess
    cint(self.port) or None)
  File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
    return socket.create_connection((port, host), timeout)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
 gaierror: [Errno -2] Name or service not known

--------------
[2015-02-14 08:11:09 +0000] [2463] [INFO] Starting gunicorn 19.2.1
[2015-02-14 08:11:09 +0000] [2463] [INFO] Listening at: http://127.0.0.1:8000 (2463)
[2015-02-14 08:11:09 +0000] [2463] [INFO] Using worker: sync
[2015-02-14 08:11:10 +0000] [2830] [INFO] Booting worker with pid: 2830
[2015-02-14 08:11:10 +0000] [2832] [INFO] Booting worker with pid: 2832
[2015-02-16 08:14:42 +0000] [2451] [INFO] Starting gunicorn 19.2.1
[2015-02-16 08:14:42 +0000] [2451] [INFO] Listening at: http://127.0.0.1:8000 (2451)
[2015-02-16 08:14:42 +0000] [2451] [INFO] Using worker: sync
[2015-02-16 08:14:42 +0000] [2473] [INFO] Booting worker with pid: 2473
[2015-02-16 08:14:42 +0000] [2474] [INFO] Booting worker with pid: 2474
[2015-02-16 09:49:46 +0000] [2438] [INFO] Starting gunicorn 19.2.1
[2015-02-16 09:49:46 +0000] [2438] [INFO] Listening at: http://127.0.0.1:8000 (2438)
[2015-02-16 09:49:46 +0000] [2438] [INFO] Using worker: sync
[2015-02-16 09:49:46 +0000] [2968] [INFO] Booting worker with pid: 2968
[2015-02-16 09:49:46 +0000] [2969] [INFO] Booting worker with pid: 2969
[2015-02-16 10:01:28 +0000] [2455] [INFO] Starting gunicorn 19.2.1
[2015-02-16 10:01:28 +0000] [2455] [INFO] Listening at: http://127.0.0.1:8000 (2455)
[2015-02-16 10:01:28 +0000] [2455] [INFO] Using worker: sync
[2015-02-16 10:01:28 +0000] [2997] [INFO] Booting worker with pid: 2997
[2015-02-16 10:01:28 +0000] [2998] [INFO] Booting worker with pid: 2998
[2015-02-17 08:38:50 +0000] [2494] [INFO] Starting gunicorn 19.2.1
[2015-02-17 08:38:50 +0000] [2494] [INFO] Listening at: http://127.0.0.1:8000 (2494)
[2015-02-17 08:38:50 +0000] [2494] [INFO] Using worker: sync
[2015-02-17 08:38:50 +0000] [2516] [INFO] Booting worker with pid: 2516
[2015-02-17 08:38:50 +0000] [2517] [INFO] Booting worker with pid: 2517
[2015-02-18 08:35:02 +0000] [2493] [INFO] Starting gunicorn 19.2.1
[2015-02-18 08:35:02 +0000] [2493] [INFO] Listening at: http://127.0.0.1:8000 (2493)
[2015-02-18 08:35:02 +0000] [2493] [INFO] Using worker: sync
[2015-02-18 08:35:02 +0000] [2702] [INFO] Booting worker with pid: 2702
[2015-02-18 08:35:02 +0000] [2703] [INFO] Booting worker with pid: 2703
[2015-02-19 08:04:49 +0000] [2489] [INFO] Starting gunicorn 19.2.1
[2015-02-19 08:04:49 +0000] [2489] [INFO] Listening at: http://127.0.0.1:8000 (2489)
[2015-02-19 08:04:49 +0000] [2489] [INFO] Using worker: sync
[2015-02-19 08:04:49 +0000] [2761] [INFO] Booting worker with pid: 2761
[2015-02-19 08:04:49 +0000] [2904] [INFO] Booting worker with pid: 2904

2015-02-19 15:54:40,035 Request Error 
 site: pruebas.local
 form: {'action': u'Save',
 'cmd': u'frappe.widgets.form.save.savedocs',
 'doc': u'{"always_use_login_id_as_sender":1,"modified_by":"Administrator","name":"Outgoing Email Settings","footer":"<div style=\\"padding: 7px; text-align: right; color: #888\\"><small>Sent via\\n\\t<a style=\\"color: #888\\" href=\\"http://erpnext.org\\">ERPNext</a></div>","creation":"2015-02-14 01:04:44.624911","enabled":1,"modified":"2015-02-14 01:04:45.920237","doctype":"Outgoing Email Settings","use_ssl":0,"owner":"Administrator","docstatus":0,"__last_sync_on":"2015-02-19T20:54:03.763Z","__unsaved":1,"mail_server":"erpnext@liberorbis.com","mail_port":587,"mail_login":"erpnext@liberorbis.com","auto_email_id":"erpnext@liberorbis.com","mail_password":"liberorbis2015"}'}

Traceback (innermost last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 49, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 66, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 89, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 532, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/widgets/form/save.py", line 18, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 183, in save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 437, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 412, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 496, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 479, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 406, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/outgoing_email_settings/outgoing_email_settings.py", line 29, in validate
    sess = smtpserver.sess
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/email_lib/smtp.py", line 85, in sess
    cint(self.port) or None)
  File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
    return socket.create_connection((port, host), timeout)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
 gaierror: [Errno -2] Name or service not known

--------------

2015-02-19 15:55:11,192 Request Error 
 site: pruebas.local
 form: {'action': u'Save',
 'cmd': u'frappe.widgets.form.save.savedocs',
 'doc': u'{"always_use_login_id_as_sender":1,"modified_by":"Administrator","name":"Outgoing Email Settings","footer":"<div style=\\"padding: 7px; text-align: right; color: #888\\"><small>Sent via\\n\\t<a style=\\"color: #888\\" href=\\"http://erpnext.org\\">ERPNext</a></div>","creation":"2015-02-14 01:04:44.624911","enabled":1,"modified":"2015-02-14 01:04:45.920237","doctype":"Outgoing Email Settings","use_ssl":0,"owner":"Administrator","docstatus":0,"__last_sync_on":"2015-02-19T20:54:03.763Z","__unsaved":1,"mail_server":"erpnext@liberorbis.com","mail_port":587,"mail_login":"erpnext@liberorbis.com","auto_email_id":"erpnext@liberorbis.com","mail_password":"liberorbis2015"}'}

Traceback (innermost last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 49, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 66, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 89, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 532, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/widgets/form/save.py", line 18, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 183, in save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 437, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 412, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 496, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 479, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 406, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/outgoing_email_settings/outgoing_email_settings.py", line 29, in validate
    sess = smtpserver.sess
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/email_lib/smtp.py", line 85, in sess
    cint(self.port) or None)
  File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
    return socket.create_connection((port, host), timeout)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
 gaierror: [Errno -2] Name or service not known

--------------

2015-02-19 16:07:27,889 Request Error 
 site: pruebas.local
 form: {'action': u'Save',
 'cmd': u'frappe.widgets.form.save.savedocs',
 'doc': u'{"always_use_login_id_as_sender":0,"modified_by":"Administrator","name":"Outgoing Email Settings","footer":"<div style=\\"padding: 7px; text-align: right; color: #888\\"><small>Sent via\\n\\t<a style=\\"color: #888\\" href=\\"http://erpnext.org\\">ERPNext</a></div>","creation":"2015-02-14 01:04:44.624911","enabled":1,"modified":"2015-02-14 01:04:45.920237","doctype":"Outgoing Email Settings","use_ssl":0,"owner":"Administrator","docstatus":0,"__last_sync_on":"2015-02-19T21:06:30.432Z","__unsaved":1,"mail_server":"smtp.liberorbis.com","mail_port":587,"mail_login":"erpnext@liberorbis.com","auto_email_id":"erpnext@liberorbis.com","mail_password":"liberorbis2015"}'}

Traceback (innermost last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 49, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 66, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 89, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 532, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/widgets/form/save.py", line 18, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 183, in save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 437, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 412, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 496, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 479, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 406, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/outgoing_email_settings/outgoing_email_settings.py", line 29, in validate
    sess = smtpserver.sess
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/email_lib/smtp.py", line 85, in sess
    cint(self.port) or None)
  File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
    return socket.create_connection((port, host), timeout)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
 gaierror: [Errno -2] Name or service not known

--------------
[2015-02-20 08:18:23 +0000] [2501] [INFO] Starting gunicorn 19.2.1
[2015-02-20 08:18:23 +0000] [2501] [INFO] Listening at: http://127.0.0.1:8000 (2501)
[2015-02-20 08:18:23 +0000] [2501] [INFO] Using worker: sync
[2015-02-20 08:18:23 +0000] [2749] [INFO] Booting worker with pid: 2749
[2015-02-20 08:18:24 +0000] [2751] [INFO] Booting worker with pid: 2751
